# Generated by Django 2.2.4 on 2019-08-13 20:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('ID', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('mtype', models.CharField(max_length=120)),
                ('primTitle', models.CharField(max_length=120)),
                ('originalTitle', models.CharField(max_length=120)),
                ('isAdult', models.BooleanField()),
                ('startyear', models.DecimalField(decimal_places=0, max_digits=10)),
                ('endyear', models.DecimalField(decimal_places=0, max_digits=10)),
                ('runtime', models.DecimalField(decimal_places=0, max_digits=10)),
                ('genres', models.CharField(max_length=120)),
                ('isBooked', models.BooleanField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10000)),
                ('poster', models.CharField(max_length=120)),
                ('description', models.TextField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='store.Media')),
                ('price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='store.Media')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Booked',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='store.Media')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
