# Generated by Django 2.2.4 on 2019-08-20 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20190814_0715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='endyear',
        ),
        migrations.RemoveField(
            model_name='product',
            name='mtype',
        ),
        migrations.RemoveField(
            model_name='product',
            name='primTitle',
        ),
        migrations.RemoveField(
            model_name='product',
            name='startyear',
        ),
    ]
