# Generated by Django 2.2.4 on 2019-09-02 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20190820_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookedproduct',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='store.Client'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='store.Client'),
        ),
    ]
